<a href="https://colab.research.google.com/github/srushtitikekar/srushti_tikekar/blob/main/Pytorch_Basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("I am excited to learn!!")

I am excited to learn!!


2.0.1+cu118


##00 Pytorch Fundamentals

Resource Notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/





In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib as lib
print(torch.__version__)



2.0.1+cu118


In [3]:
## Introduction to Tensors

## creating tensors

Pytorch tensors are created using 'torch.Tensor()' = https://pytorch.org/docs/stable/tensors.html


SyntaxError: ignored

In [4]:
#scalar

scalar = torch.tensor(7)

In [5]:
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
# get tensor back as python int
scalar.item()

7

In [8]:
#vector

vector = torch.tensor([7,7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
#Matrix

Matrix = torch.tensor([[1,2],[3,4]])

In [12]:
Matrix

tensor([[1, 2],
        [3, 4]])

In [13]:
Matrix.ndim

2

In [14]:
Matrix.shape

torch.Size([2, 2])

In [15]:
Matrix[0]

tensor([1, 2])

In [16]:
# TENSOR

TENSOR = torch.tensor([[[1,2,3],[4,5,6],[2,5,4]]])

In [ ]:
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [2, 5, 4]]])

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [2, 5, 4]])

In [17]:
random_tensor = torch.rand(size=(4,4,4))

In [18]:
random_tensor.ndim

3

In [19]:
random_tensor.shape

torch.Size([4, 4, 4])

In [20]:
random_tensor

tensor([[[0.0631, 0.7725, 0.3525, 0.7340],
         [0.2172, 0.4076, 0.1328, 0.9821],
         [0.0982, 0.7764, 0.8247, 0.2655],
         [0.1048, 0.0570, 0.6159, 0.3859]],

        [[0.6125, 0.5336, 0.3627, 0.3430],
         [0.4975, 0.3571, 0.1568, 0.7310],
         [0.3631, 0.7213, 0.9682, 0.2826],
         [0.3717, 0.1340, 0.2851, 0.3195]],

        [[0.7401, 0.0996, 0.4462, 0.4402],
         [0.5152, 0.0846, 0.1510, 0.1637],
         [0.0758, 0.7842, 0.4406, 0.8297],
         [0.7855, 0.4193, 0.0123, 0.2670]],

        [[0.1843, 0.4796, 0.9786, 0.3587],
         [0.6316, 0.1038, 0.8746, 0.9774],
         [0.1563, 0.4372, 0.2799, 0.6869],
         [0.6770, 0.5052, 0.4294, 0.6399]]])

In [21]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [24]:
#All zeros

torch_z = torch.ones(size=(3,4))

In [26]:
torch_z.dtype

torch.float32

In [31]:
one1=torch.arange(start=0, end=10,step=2)

In [32]:
f1 = torch.zeros_like(one1)

In [33]:
f1

tensor([0, 0, 0, 0, 0])